#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("WeightTracker.Resource", IsApplication=true)]

namespace WeightTracker
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070000
			public const int ChartDataArray = 2131165184;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050009
			public const int amount_changed_left_margin = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int amount_changed_width = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int date_label_width = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int date_picker_height = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int date_picker_width = 2131034123;
			
			// aapt resource value: 0x7f050004
			public const int display_header_label_value_width = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int display_header_label_width = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int edit_text_height = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int edit_text_left_margin = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int edit_text_text_size = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int edit_text_width = 2131034119;
			
			// aapt resource value: 0x7f050001
			public const int header_label_height = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int header_label_text_size = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int header_label_width = 2131034114;
			
			// aapt resource value: 0x7f050012
			public const int list_view_height = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int list_view_top_margin = 2131034131;
			
			// aapt resource value: 0x7f050018
			public const int row_total_change_height = 2131034136;
			
			// aapt resource value: 0x7f050017
			public const int row_total_change_left_margin = 2131034135;
			
			// aapt resource value: 0x7f050014
			public const int row_weight_change_height = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int row_weight_change_left_margin = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int row_weight_change_top_margin = 2131034134;
			
			// aapt resource value: 0x7f050010
			public const int save_button_height = 2131034128;
			
			// aapt resource value: 0x7f05000e
			public const int save_button_left_margin = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int save_button_top_margin = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int save_button_width = 2131034129;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add_new = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int trash = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09002b
			public const int AbsChange = 2131296299;
			
			// aapt resource value: 0x7f09002c
			public const int AbsChangeTotal = 2131296300;
			
			// aapt resource value: 0x7f090027
			public const int AbsTextBox = 2131296295;
			
			// aapt resource value: 0x7f090050
			public const int ActionSetCurrentUser = 2131296336;
			
			// aapt resource value: 0x7f090052
			public const int ActionSettings = 2131296338;
			
			// aapt resource value: 0x7f090051
			public const int ActionViewCharts = 2131296337;
			
			// aapt resource value: 0x7f09004f
			public const int ActionViewUsers = 2131296335;
			
			// aapt resource value: 0x7f09004d
			public const int AddNewButton = 2131296333;
			
			// aapt resource value: 0x7f090002
			public const int BarChartDataSpinner = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int BarChartLinearLayout = 2131296259;
			
			// aapt resource value: 0x7f090025
			public const int ChestChange = 2131296293;
			
			// aapt resource value: 0x7f090026
			public const int ChestChangeTotal = 2131296294;
			
			// aapt resource value: 0x7f090021
			public const int ChestTextBox = 2131296289;
			
			// aapt resource value: 0x7f090019
			public const int Date = 2131296281;
			
			// aapt resource value: 0x7f090014
			public const int DisplayAbs = 2131296276;
			
			// aapt resource value: 0x7f09000e
			public const int DisplayChest = 2131296270;
			
			// aapt resource value: 0x7f090006
			public const int DisplayHips = 2131296262;
			
			// aapt resource value: 0x7f090008
			public const int DisplayLeftArm = 2131296264;
			
			// aapt resource value: 0x7f09000f
			public const int DisplayLeftCalf = 2131296271;
			
			// aapt resource value: 0x7f090009
			public const int DisplayLeftThigh = 2131296265;
			
			// aapt resource value: 0x7f09000b
			public const int DisplayRightArm = 2131296267;
			
			// aapt resource value: 0x7f090012
			public const int DisplayRightCalf = 2131296274;
			
			// aapt resource value: 0x7f09000c
			public const int DisplayRightThigh = 2131296268;
			
			// aapt resource value: 0x7f090016
			public const int DisplayTotalSizeChange = 2131296278;
			
			// aapt resource value: 0x7f090018
			public const int DisplayTotalWeightChange = 2131296280;
			
			// aapt resource value: 0x7f090011
			public const int DisplayWaist = 2131296273;
			
			// aapt resource value: 0x7f090005
			public const int DisplayWeight = 2131296261;
			
			// aapt resource value: 0x7f09002e
			public const int HipsChange = 2131296302;
			
			// aapt resource value: 0x7f09002f
			public const int HipsChangeTotal = 2131296303;
			
			// aapt resource value: 0x7f09002a
			public const int HipsTextBox = 2131296298;
			
			// aapt resource value: 0x7f09001f
			public const int LeftArmChange = 2131296287;
			
			// aapt resource value: 0x7f090020
			public const int LeftArmChangeTotal = 2131296288;
			
			// aapt resource value: 0x7f09001b
			public const int LeftArmTextBox = 2131296283;
			
			// aapt resource value: 0x7f09003a
			public const int LeftCalfChange = 2131296314;
			
			// aapt resource value: 0x7f09003b
			public const int LeftCalfChangeTotal = 2131296315;
			
			// aapt resource value: 0x7f090035
			public const int LeftCalfTextBox = 2131296309;
			
			// aapt resource value: 0x7f090032
			public const int LeftThighChange = 2131296306;
			
			// aapt resource value: 0x7f090033
			public const int LeftThighChangeTotal = 2131296307;
			
			// aapt resource value: 0x7f09002d
			public const int LeftThighTextBox = 2131296301;
			
			// aapt resource value: 0x7f090004
			public const int MeasurementBarChart = 2131296260;
			
			// aapt resource value: 0x7f090045
			public const int MeasurementsListView = 2131296325;
			
			// aapt resource value: 0x7f090041
			public const int PrevMeasurementChangeTotal = 2131296321;
			
			// aapt resource value: 0x7f090022
			public const int RightArmChange = 2131296290;
			
			// aapt resource value: 0x7f090023
			public const int RightArmChangeTotal = 2131296291;
			
			// aapt resource value: 0x7f09001e
			public const int RightArmTextBox = 2131296286;
			
			// aapt resource value: 0x7f09003e
			public const int RightCalfChange = 2131296318;
			
			// aapt resource value: 0x7f09003f
			public const int RightCalfChangeTotal = 2131296319;
			
			// aapt resource value: 0x7f090039
			public const int RightCalfTextBox = 2131296313;
			
			// aapt resource value: 0x7f090036
			public const int RightThighChange = 2131296310;
			
			// aapt resource value: 0x7f090037
			public const int RightThighChangeTotal = 2131296311;
			
			// aapt resource value: 0x7f090031
			public const int RightThighTextBox = 2131296305;
			
			// aapt resource value: 0x7f090047
			public const int RowDate = 2131296327;
			
			// aapt resource value: 0x7f090046
			public const int RowDeleteButton = 2131296326;
			
			// aapt resource value: 0x7f090049
			public const int RowTotalChange = 2131296329;
			
			// aapt resource value: 0x7f09004a
			public const int RowWeightChange = 2131296330;
			
			// aapt resource value: 0x7f09003d
			public const int SaveButton = 2131296317;
			
			// aapt resource value: 0x7f090042
			public const int TotalMeasurementChange = 2131296322;
			
			// aapt resource value: 0x7f09004e
			public const int UsersListView = 2131296334;
			
			// aapt resource value: 0x7f090028
			public const int WaistChange = 2131296296;
			
			// aapt resource value: 0x7f090029
			public const int WaistChangeTotal = 2131296297;
			
			// aapt resource value: 0x7f090024
			public const int WaistTextBox = 2131296292;
			
			// aapt resource value: 0x7f09001c
			public const int WeightChange = 2131296284;
			
			// aapt resource value: 0x7f09001d
			public const int WeightChangeTotal = 2131296285;
			
			// aapt resource value: 0x7f09001a
			public const int WeightTextBox = 2131296282;
			
			// aapt resource value: 0x7f090000
			public const int linearLayout1 = 2131296256;
			
			// aapt resource value: 0x7f090034
			public const int linearLayout10 = 2131296308;
			
			// aapt resource value: 0x7f090038
			public const int linearLayout11 = 2131296312;
			
			// aapt resource value: 0x7f09003c
			public const int linearLayout12 = 2131296316;
			
			// aapt resource value: 0x7f090040
			public const int linearLayout13 = 2131296320;
			
			// aapt resource value: 0x7f090043
			public const int linearLayout14 = 2131296323;
			
			// aapt resource value: 0x7f090044
			public const int linearLayout15 = 2131296324;
			
			// aapt resource value: 0x7f090007
			public const int linearLayout2 = 2131296263;
			
			// aapt resource value: 0x7f09000a
			public const int linearLayout3 = 2131296266;
			
			// aapt resource value: 0x7f09000d
			public const int linearLayout4 = 2131296269;
			
			// aapt resource value: 0x7f090010
			public const int linearLayout5 = 2131296272;
			
			// aapt resource value: 0x7f090013
			public const int linearLayout6 = 2131296275;
			
			// aapt resource value: 0x7f090015
			public const int linearLayout7 = 2131296277;
			
			// aapt resource value: 0x7f090017
			public const int linearLayout8 = 2131296279;
			
			// aapt resource value: 0x7f090030
			public const int linearLayout9 = 2131296304;
			
			// aapt resource value: 0x7f090001
			public const int textView1 = 2131296257;
			
			// aapt resource value: 0x7f09004b
			public const int textView2 = 2131296331;
			
			// aapt resource value: 0x7f090048
			public const int textView3 = 2131296328;
			
			// aapt resource value: 0x7f09004c
			public const int textView5 = 2131296332;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ChartViewer = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DisplayMeasurement = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MeasurementRow = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ViewUsers = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int MainMenu = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int bar_spinner_prompt = 2131099649;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int prefs = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
